apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd

spec:
  project: default

  source:
    repoURL: git@github.com:YOUR_USER/cluster-gitops.git
    targetRevision: main
    path: apps/portfolio/base

  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
