apiVersion: v1
kind: ConfigMap
metadata:
  name: portfolio-html
  namespace: portfolio
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Status</title>
    </head>
    <body style="background-color: #FF00FF; display:flex; justify-content:center; align-items:center; height:100vh;">
      <h1>Ingress-Successful</h1>
    </body>
    </html>
