alertmanager:
  enabled: true
prometheus:
  prometheusSpec:
    retention: 10d
    # Fixes the Kustomize parser mismatch by using a direct storage mapping
    storage:
      volumeClaimTemplate:
        apiVersion: v1
        kind: PersistentVolumeClaim
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "local-path"
          resources:
            requests:
              storage: 10Gi
grafana:
  enabled: true
  ingress:
    enabled: false #disabled because handled via custom ingress.yaml
  grafana.ini:
    server:
      root_url: https://grafana.ravijey.com
