apiVersion: apps/v1
kind: Deployment
metadata:
  name: astroneer-server
  namespace: astroneer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: astroneer-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: astroneer-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: node2-48ecc894

      # 1. Bypasses pod network isolation, binding directly to node2's physical interfaces
      hostNetwork: true

      containers:
        - name: astroneer
          image: ghcr.io/birdhimself/astroneer-server:latest
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
          ports:
            - containerPort: 7777
              protocol: UDP
              name: game-port
          env:
            #local Ip
            - name: ASTRO_SERVER_PUBLIC_IP
              value: "192.168.1.163"
            - name: ASTRO_SERVER_PORT
              value: "7777"
            - name: DEBUG
              value: "false"
            - name: DISABLE_ENCRYPTION
              value: "true"
            - name: ASTRO_SERVER_DISABLE_ENCRYPTION
              value: "true"
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
            requests:
              memory: 2Gi
              cpu: "1"
          volumeMounts:
            - name: server-data
              mountPath: /astrotux/AstroneerServer/Astro/Saved
      volumes:
        - name: server-data
          persistentVolumeClaim:
            claimName: astroneer-pvc
