apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: astroneer

resources:
  - deployment.yaml
  - pvc.yaml

# Keeps all resources cleanly labeled
commonLabels:
  app: astroneer-server
