apiVersion: v1
kind: Service
metadata:
  name: astroneer-server
spec:
  type: NodePort
  selector:
    app: astroneer-server
  ports:
    - name: game-port
      protocol: UDP
      port: 7777 # The port the cluster pods use internally
      targetPort: 7777 # The port inside the container
      nodePort: 37777 # The port exposed on node2's host/Tailscale IP
